// Code generated by "stringer -type=VerbType"; DO NOT EDIT.

package verb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VBP-0]
	_ = x[VBD-1]
	_ = x[VBN-2]
	_ = x[VBZ-3]
	_ = x[VBG-4]
}

const _VerbType_name = "VBPVBDVBNVBZVBG"

var _VerbType_index = [...]uint8{0, 3, 6, 9, 12, 15}

func (i VerbType) String() string {
	if i < 0 || i >= VerbType(len(_VerbType_index)-1) {
		return "VerbType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VerbType_name[_VerbType_index[i]:_VerbType_index[i+1]]
}
